# Copyright (c) it4fi. All rights reserved. {{{1
# Licensed under the MIT License.

version: '3'
services:
  go: # {{{1
    image: golang
    volumes:
      - ./go:/root
      - /home/ubuntu/product/stellar/horizon/go:/go/src/github.com/stellar/go
      - /home/ubuntu/go1.16/bin:/go/bin
    working_dir: /go/src/github.com/stellar/go
    command: /root/dk-horizon-install.sh github.com/stellar/go/services/horizon
  core: # {{{1
    build:
      context: ./core
    volumes:
      - ./core/core-install.sh:/core-install.sh
        #- /home/ubuntu/product/stellar/stellar-core:/home/vscode/stellar-core
      - ./usr_local:/usr/local
    command: /core-install.sh stellar-core
